#!/bin/sh

if [ -z "$1" ]; then
  echo "You may need to execute the follwoing command to use \"$(basename $0)\" at the first time."
  echo
  echo 'export ETCDCTL_PEERS="$(vagrant ssh-config core-1 | sed -n "s/[ ]*HostName[ ]*//gp"):4001"'
  exit 1
fi

etcdctl -C "${ETCDCTL_PEERS}" "$@"
